### PR TITLE
Add restore card functionality

### PR DESCRIPTION
**Pull request by Luk-z**
This can be used for example with a back button

### CODE REVIEW

**Comment by 3DJakob** [comment]
Hello @Luk-z! Looks like a nice feature addition! I would love for you to also update the readme to include the added api usage. I have a lot of work right now but if you want to speed up the merge process please also fork my [tinder-card-demo](https://github.com/3DJakob/react-tinder-card-demo) repository and ad this to the advanced example in some way. That would be great for me to test as well as a good example once it is released.

**Comment by Luk-z** [comment]
Hi @3DJakob, i will! Currently I'm working on another feature to swap based on touchend / mouseup position, not on speed. Then i will update readme and i will make a demo with the new features.

**Comment by 3DJakob** [comment]
> Hi @3DJakob, i will! Currently I'm working on another feature to swap based on touchend / mouseup position, not on speed. Then i will update readme and i will make a demo with the new features.

I see. Please do not make one pull request with multiple features/changes though! Also, I deliberately made it detect swipes on velocity rather than position so I won't merge a change that replaces that. However if you ad another prop like `postitionBasedSwipe: boolean` that is fine by me. Thank you for your contributions!

**Comment by Luk-z** [comment]
>Please do not make one pull request with multiple features/changes though!
I'm adding features to your library because my company need it, I will continue add that features on master branch. 
I think it's better delete this pull request, after, when I completed my work, I will create separate pull requests for each feature. Don't you think too?

>However if you add another prop like postitionBasedSwipe: boolean that is fine by me
Yes that's the way I'm working. By default the library works as you provided, every feature I add is disabled by default.

**Comment by 3DJakob** [comment]
@Luk-z Yes that sounds good. Please do it like that! Once you have

- Extending rather than changing functionality
- Documented in the readme and prop types
- One functionality per merge

I will be happy to add this! 💯

**Comment by Luk-z** [comment]
Closed as other atomic PR will be made

**Pull request closed without merging**
