### PR TITLE
Indicate compatibility with React 17

### PR DESCRIPTION
**Pull request by LinusU**

### CODE REVIEW

**Comment by okwuosa34** [comment]
I am having an issue trying to run the install from react@18.2

**Comment by okwuosa34** [comment]
> 

Onyinyes-MBP:couplesapp Onyinye34$ npm install --save react-tinder-card
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: couplesapp@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from react-tinder-card@1.4.5
npm ERR! node_modules/react-tinder-card
npm ERR!   react-tinder-card@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/Onyinye34/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Onyinye34/.npm/_logs/2022-06-23T01_38_06_726Z-debug-0.log

**Comment by Datta2119** [comment]
@okwuosa34 same thing goes around for me also

**Comment by okwuosa34** [comment]
@Datta2119 I found a workaround. Downgrade your react to version 17

**Pull request merged**
